# Generated by Django 3.0.4 on 2020-04-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus', '0003_auto_20200409_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_range',
            field=models.CharField(default='', max_length=254),
        ),
    ]
