# Generated by Django 3.0.4 on 2020-04-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus', '0005_auto_20200409_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='port_range',
            field=models.CharField(default='', max_length=254),
        ),
    ]
