# Generated by Django 3.0.4 on 2020-04-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus', '0006_scan_port_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ftp_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='http_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='https_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='rdp_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='smb_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='telnet_present',
            field=models.BooleanField(default=False),
        ),
    ]
